TREE GROWTH INVESTIGATIONS
========================================================
First load everything in...
```{r echo=FALSE}
library(plyr)
library(ggplot2)
library(grid)
library(gridExtra)
library(stargazer)
library(ggthemes)
library(lme4)
library(extrafont)

setwd("/Users/danielgodwin/Dropbox/Graduate School/Dissertation/FireEscapeModel_Git/")

myTheme <- theme_tufte() +
  theme(
    text = element_text(family="Arial", size=14),
        axis.line = element_line(size = .3)
    )

```


```{r precursor,warning=FALSE}
Melon_Sites <- read.csv("Data/Sites/Mellon_Tree.csv")
Melon_Species <- read.csv("Data/MeasuredGrowth/MellonGrant/MellonGrant_Species.csv")
Melon_Growth <- read.csv("Data/MeasuredGrowth/MellonGrant/MellonGrant_TreeGrowth_LongForm.csv")
source("Scripts/WeatherProcessor.R")
PRET2011_RINGW_LongForm <- read.csv("Data/MeasuredGrowth/TrialProject/PRET2011_RINGW_LongForm.csv")


names(Melon_Sites)[2] <- "Sample"
names(Melon_Species) <- c("Sample","Species")
names(Melon_Growth) <- c("Sample","Year","RINGW")

Melon_Master <- merge(Melon_Sites,Melon_Species, by="Sample")
Melon_Master$Species.x <- NULL

Melon_Master <- merge(Melon_Master,Melon_Growth,by="Sample")
Melon_Master$Diam <- NULL
Melon_Master$TTT <- NULL
names(Melon_Master)[3] <- "Species"

PRET2011_RINGW_LongForm$Site <- "PRE"
PRET2011_RINGW_LongForm$SPECIES <-"Terminalia sericea"
names(PRET2011_RINGW_LongForm) <- c("Sample","Year","RINGW","Site","Species")

Melon_Master <- rbind(Melon_Master,PRET2011_RINGW_LongForm)

Melon_Master$RINGW <- Melon_Master$RINGW/1000

Melon_Master <- Melon_Master[order(Melon_Master$Sample,Melon_Master$Year),]

Melon_Master <- ddply(Melon_Master,.(Sample),mutate,Growth = cumsum(RINGW))

Melon_Master$EstCrossSection <- (Melon_Master$Growth)^2 * pi
Melon_Master$EstBasalDiameter <- (Melon_Master$Growth) * 2

Melon_Master <- ddply(Melon_Master,.(Sample),mutate,YearOfGrowth = Year - min(Year)+1)

Melon_AllWx <- merge(Melon_Master,Kruger_Wx_Combined,by.x=c("Year","Site"),by.y=c("Year","Station"))

MAP <- read.csv("Data/Weather/Kruger_MAP.csv")
Melon_AllWx <- merge(Melon_AllWx,MAP,by.x="Site",by.y="Station")




COMO_naive_DF <- subset(Melon_Master,Species =="Colophospermum mopane")
COAP_naive_DF <- subset(Melon_Master,Species =="Combretum apiculatum")
TESE_naive_DF <- subset(Melon_Master,Species =="Terminalia sericea")

COMO_naiveGrowth <- lm(log(EstBasalDiameter) ~ 0 + log(YearOfGrowth),data=COMO_naive_DF)
TESE_naiveGrowth <- lm(log(EstBasalDiameter) ~ 0 + log(YearOfGrowth),data=TESE_naive_DF)
COAP_naiveGrowth <- lm(log(EstBasalDiameter) ~ 0 + log(YearOfGrowth),data=COAP_naive_DF)                       



COMO_plotDF <- expand.grid(YearOfGrowth=seq(0,20))
COMO_plotDF$EstBasalDiameter <- exp(predict(COMO_naiveGrowth,COMO_plotDF))

COAP_plotDF <- expand.grid(YearOfGrowth=seq(0,20))
COAP_plotDF$EstBasalDiameter <- exp(predict(COAP_naiveGrowth,COAP_plotDF))

TESE_plotDF <- expand.grid(YearOfGrowth=seq(0,20))
TESE_plotDF$EstBasalDiameter <- exp(predict(TESE_naiveGrowth,TESE_plotDF))

TESE_plotDF$SPECIES <- "Terminalia sericea"
COMO_plotDF$SPECIES <- "Colophospermum mopane"
COAP_plotDF$SPECIES <- "Combretum apiculatum"


displayPlotted <- rbind(TESE_plotDF,COMO_plotDF)
displayPlotted <- rbind(displayPlotted,COAP_plotDF)

displayPlotted$Species <- as.factor(displayPlotted$SPECIES)
names(naive_growth)[1] <- "Site"
levels(naive_growth$Species)<- c("C. mopane","C. apiculatum","T. sericea")
levels(displayPlotted$Species)<- c("C. mopane","C. apiculatum","T. sericea")



```


```{r}
displayPlotted_plot <- ggplot(data = Melon_Master, aes(x = YearOfGrowth, y=EstBasalDiameter,colour=Species,group=Sample))
displayPlotted_plot+
  myTheme+
  ylab("log Ring Width (cm)")+
  xlab("log Age (yrs)")+
  scale_color_colorblind()+
  geom_point()+
  geom_line(aes(group=Sample))
```

```{r}
naive_growth <- Melon_AllWx[order(Melon_AllWx$Sample,Melon_AllWx$Year),]

naive_growth <- ddply(naive_growth,
                      .(Species,Site,Sample,MAP),
                      mutate,
                      TotalSize = cumsum(EstBasalDiameter),
                      Age = max(YearOfGrowth),
                      TotalLifeRain = cumsum(AnnualPrecip),
                      MeanLifeRain = mean(AnnualPrecip))

naive_growth$NaiveRate <- naive_growth$TotalSize/naive_growth$Age
```

```{r}
cumulativeSum_rate <- ggplot(data = naive_growth, aes(x = log(TotalLifeRain), y=log(NaiveRate),colour=Species,group=Sample))
cumulativeSum_rate+
  myTheme+
  ylab("log Rate of Growth (cm / yr)")+
  xlab("log Total Lifetime Rain (mm)")+
  scale_color_colorblind()+
  geom_point()+
  geom_line(aes(group=Sample))+
  facet_wrap(~Species)
```

```{r}
cumulativeSum_total <- ggplot(data = naive_growth, aes(x = log(TotalLifeRain), y=log(TotalSize),colour=Species,group=Sample))
cumulativeSum_total+
  myTheme+
  ylab("log Total Diameter (cm)")+
  xlab("log Total Lifetime Rain (mm)")+
  scale_color_colorblind()+
  geom_point()+
  geom_line(aes(group=Sample))+
  facet_wrap(~Species)
```